### ISSUE TITLE
How to use the SetSessionManager for scaling?

### ISSUE THREAD

**Issue by bigblind** [googollee/go-socket.io#74] opened 2015-03-21 10:02 UTC
As far as I can see, there's no way to serialize connections, store them in a database, retrieve them and reconstruct them, so how would that be done? An example would be very useful.

**Comment by googollee** [comment] 2015-03-21 16:58
Could you describe more detail of this feature? How to serialize a connection? Does that mean restore the status from previous connection?

**Comment by bigblind** [comment] 2015-03-21 18:03
Yeah. So let's say you're running an app in an environment where you don't have access to sticky routing. This means that a request whose connection started on server A, can suddenly be routed to server B. So what I'd like to be able to do is store the socket's state, and retrieve it by id, so that it doesn't matter where requests are routed.

**Comment by fuel-shea** [comment] 2015-05-29 17:59
+1

**Comment by hadv** [comment] 2016-03-20 08:07
+1

How can we implement web socket server on multiple nodes like socket.io?
http://socket.io/docs/using-multiple-nodes/

**Comment by erkie** [comment] 2019-02-08 09:56
Duplicate of https://github.com/googollee/go-socket.io/issues/64

**Closed by erkie** 2019-02-08 09:56 UTC
