### ISSUE TITLE
Socket.io 2.0 support

### ISSUE THREAD

**Issue by ghost** [googollee/go-socket.io#188] opened 2017-11-21 00:26 UTC
Is there anything planned for it?

I can't get it to work with [JS socket.io-client](https://github.com/socketio/socket.io-client), the connection just never seems to happen.

**Comment by utdrmac** [comment] 2017-11-21 18:55
pretty sure this project is dead

**Comment by googollee** [comment] 2017-11-21 22:14
No. I don't have time to maintain this project now. You can fork it and add the feature yourself.

**Comment by utdrmac** [comment] 2017-11-21 23:00
@googollee any official forks? any new maintainer?

**Comment by googollee** [comment] 2017-11-22 10:01
No. At least I don't know. If any one want to take it, please notice me. I
can write it in README.

**Comment by erkie** [comment] 2019-02-08 10:16
There is no active full development on this repo going on, but more contributors are very welcome to submit PR. I'm here to help get PR's merged and checked :)

**Comment by jjhesk** [comment] 2019-02-19 03:05
@googollee can you transfer the project to this guy  @erkie  to maintain it?

**Comment by jjhesk** [comment] 2019-02-19 03:36
The problems are fixed by this guy https://github.com/pschlump/socketio

**Comment by kunaldawn** [comment] 2019-05-27 08:34
Guys, any one working on it. We are using this library at prod, and getting many issues. Any plans to update or mark the project as archived and show link to actively maintained fork. Seriously dude. This is the only stable socket.io lib available and its broken AF..

**Comment by kunaldawn** [comment] 2019-05-27 08:35
@googollee can you share implementation details or any architecture diagram of this project?

**Comment by erkie** [comment] 2019-05-27 19:37
This project needs help and we mention it in every issue. Please support it by making PR’s fixing issues. Assume no help from maintainers but feel free to ask targeted questions. If you benefit from the project: we need your help. Dont just complain. We’ll help you merge fixes ASAP.

**Comment by erkie** [comment] 2019-05-27 19:38
@kunaldawn ☝️

**Comment by kunaldawn** [comment] 2019-05-28 09:52
@erkie I understand that, the problem is there is no documentation why there is v1.0 v1.4 and v1.4.1 and what are the purpose. which API is going to be supported? Latest master API is not compatible with v1.4.1. Can you get some light on it.

**Comment by kunaldawn** [comment] 2019-05-28 10:00
Why people are not directly contributing to this project, for example https://github.com/pschlump/socketio seems to fix some issues.

**Comment by erkie** [comment] 2019-05-28 10:04
@kunaldawn as per the README, the master branch aims to be compatible with version 1.4 of Socket.io. With that in mind, can we count on your passion to help this project? :) Like I've mentioned, I'd be more than happy to assist getting PR's merged. Looking forward to seeing you in the PR section soon!

**Comment by kunaldawn** [comment] 2019-05-28 15:29
@erkie let me understand the code base first, we are still using v1.0 and sometimes OnClose panics. It seems v1.4.1 has the fix (using sync.Once) but missing Broadcast feature. Let me fix my production server first, crash is causing our stateful service to fail and make us panic :P, will surely contribute if I am able to understand this big project.

**Comment by kunaldawn** [comment] 2019-05-29 12:23
hi @erkie, as per my analysis v1.0 and v1.4 has some broken api changes. Our server code architecture is written in such a way its dependent on the following apis:
- Broadcast feature form server instance #230 
- Adding On handlers to connection itself #231 

For the broadcast API #230, I have raised a PR https://github.com/googollee/go-socket.io/pull/239

Now I am working on providing On api #231 in Conn interface, but the problem is for EVENT there could be only one writer, for example of I do server.OnEvent("ns", "event_1", func..) and conn.On("event_1", func..) only one of listeners ack can be written back. Currently i have decided that if direct On handlers are added they will get higher preference that global namespace handlers.

**@erkie can you suggest some thing on what will be the proper way to bring On(event string, func...) #231 API back to Conn interface.**

**Comment by juicechu** [comment] 2020-07-15 14:27
I found `ambelovsky` had finish socket.io 2.0 support . https://github.com/ambelovsky/gosf-socketio

**Closed** 2024-09-29 15:20 UTC
Labels: new-feature, help-wanted, v2
