### ISSUE TITLE
we meet "upgrading" error frequently

### ISSUE THREAD

**Issue by crazyou** [googollee/go-socket.io#193] opened 2018-02-09 15:17 UTC
when we use the websocket , we meet "upgrading" error frequently,  sothat we can not emit the msg to web by websocket
does anybody meet the situation, and is it a bug ?  or we have some method to resolve it
Thanks

**Comment by liqi7417** [comment] 2018-06-28 06:36
it is a big problem, client send upgrade req to server, then send '2probe' and server send '3probe' back, but client not send '5' to upgrade to websocket, so server blocks in upgrading status
i think server should send res back in polling transport rather than waiting for websocket upgrade.

**Comment by Sreevani871** [comment] 2019-01-28 13:02
Is there any update on this. In production we are facing this problem frequently so that customer unable to receive any messages sent on the socket since the socket stuck in upgrading status. It would be great help if anyone suggest fix for this.

**Comment by googollee** [comment] 2019-01-30 09:36
I'm very busy recently, so I'm afraid I don't have time on this project.
Welcome to pr.

>

**Comment by erkie** [comment] 2019-02-08 09:45
@Sreevani871 can you perhaps see if you can find a sample project or code sample that will reproduce this? It would really help us debug it. :)

**Comment by Sreevani871** [comment] 2019-02-18 06:49
@erkie We will try to reproduce the same in the local environment and will update the code

**Comment by erkie** [comment] 2019-02-18 11:33
@Sreevani871 great thanks! Please note that a major upgrade happened during the time you wrote the issue and today. We have merged the branch major rewrite 1.4 into master, which supports a higher version of Socket.IO.

**Comment by Sreevani871** [comment] 2019-02-20 03:49
@erkie Thanks for the update.
Can you please help me to migrate our code to lastest master?
	
Existing Code: 
    
    sserver, err := sio.NewServer(nil)

	sserver.SetMaxConnection(50000)                           // Set Max socket connections to handle
	sserver.SetPingInterval(time.Duration(30) * time.Second) // 30 seconds
	sserver.SetPingTimeout(time.Duration(45) * time.Second)   // 45 seconds

    sserver.SetAllowRequest(auth.AuthenticateSocketIORequest)
	// On new connection
	sserver.On("connection", func(so sio.Socket) {

		// ========== Handle Socket Events  ========== ========== ==========

		so.On("connect", func() {  })

		so.On("connecting", func() { })

		so.On("disconnect", func() {  })

		so.On("connect_failed", func() {  })

		so.On("error", func(e interface{}) {  })

		so.On("reconnect_failed", func() {  })

		so.On("reconnect", func() { })

		so.On("reconnecting", func() { })

		so.On("disconnection", func() {

		})

		so.On("message", func(msg string) {
		
		})
	})

Refactored Code: Can you please tell how I can modify the above code to make it compatible with laster master

And In 0.9.x we have so.Emit() returns an error but in latest master, it does not. How we can handle error cases such as `EOF` and `upgrading` errors of the socket during emitting.

**Comment by erkie** [comment] 2020-09-11 07:00
Not 1.4 version. So closing. Create a new issue if it still happens in 1.4

**Closed by erkie** 2020-09-11 07:00 UTC
Labels: info-needed
