### ISSUE TITLE
Did you forget to Close() the ReadCloser from NextReader?

### ISSUE THREAD

**Issue by Karafs** [googollee/go-socket.io#399] opened 2020-10-23 16:10 UTC
What is this log on the server-side?
And what will happen if we emit to a conn that has closed?

Did you forget to Close() the ReadCloser from NextReader?

**Comment by mrfoe7** [comment] 2021-04-14 08:42
> What is this log on the server-side?

logs does not implemented by server-side

> Did you forget to Close() the ReadCloser from NextReader?

Do you can send some source code?

**Comment by Karafs** [comment] 2021-05-02 06:45
There is a go file (wrapper.go) that includes a function by name (newRcWrapper). This function prints a the above message:

func newRcWrapper(l *sync.Mutex, r io.Reader) rcWrapper {
	timer := time.NewTimer(30 * time.Second)
	q := make(chan struct{})
	go func() {
		select {
		case <-q:
		case <-timer.C:
			fmt.Println("Did you forget to Close() the ReadCloser from NextReader?")
		}
	}()
	return rcWrapper{
		nagTimer: timer,
		quitNag:  q,
		l:        l,
		Reader:   r,
	}
}

**Comment by Karafs** [comment] 2021-05-02 06:47
> There is a go file (wrapper.go) that includes a function by name (newRcWrapper). This function prints a the above message:
> 
> func newRcWrapper(l *sync.Mutex, r io.Reader) rcWrapper {
> timer := time.NewTimer(30 * time.Second)
> q := make(chan struct{})
> go func() {
> select {
> case <-q:
> case <-timer.C:
> fmt.Println("Did you forget to Close() the ReadCloser from NextReader?")
> }
> }()
> return rcWrapper{
> nagTimer: timer,
> quitNag: q,
> l: l,
> Reader: r,
> }
> }

@mrfoe7

**Comment by piksonGit** [comment] 2021-05-06 14:48
Hey, I got the same notice "resume
resume
resume
resume
resume
resume
Did you forget to Close() the ReadCloser from NextReader?
resume
resume
Did you forget to Close() the ReadCloser from NextReader?
Did you forget to Close() the ReadCloser from NextReader?
Did you forget to Close() the ReadCloser from NextReader?
resume
resume
Did you forget to Close() the ReadCloser from NextReader?
Did you forget to Close() the ReadCloser from NextReader?
Did you forget to Close() the ReadCloser from NextReader?
resume
Did you forget to Close() the ReadCloser from NextReader?
Did you forget to Close() the ReadCloser from NextReader?
Did you forget to Close() the ReadCloser from NextReader?
Did you forget to Close() the ReadCloser from NextReader?
Did you forget to Close() the ReadCloser from NextReader?
"

have you solved the problem?

**Comment by Karafs** [comment] 2021-05-07 09:37
> Hey, I got the same notice "resume
> resume
> resume
> resume
> resume
> resume
> Did you forget to Close() the ReadCloser from NextReader?
> resume
> resume
> Did you forget to Close() the ReadCloser from NextReader?
> Did you forget to Close() the ReadCloser from NextReader?
> Did you forget to Close() the ReadCloser from NextReader?
> resume
> resume
> Did you forget to Close() the ReadCloser from NextReader?
> Did you forget to Close() the ReadCloser from NextReader?
> Did you forget to Close() the ReadCloser from NextReader?
> resume
> Did you forget to Close() the ReadCloser from NextReader?
> Did you forget to Close() the ReadCloser from NextReader?
> Did you forget to Close() the ReadCloser from NextReader?
> Did you forget to Close() the ReadCloser from NextReader?
> Did you forget to Close() the ReadCloser from NextReader?
> "
> 
> have you solved the problem?

Not yet!

**Comment by mrfoe7** [comment] 2021-05-07 10:45
Hey, Dude!
Thanks for your issue. I''ll check your case into this week. is it big problem in your usage?
Relax and don't flame

**Comment by Karafs** [comment] 2021-05-07 10:56
> Hey, Dude!
> Thanks for your issue. I''ll check your case into this week. is it big problem in your usage?
> Relax and don't flame

thanks.

**Comment by iGoogle-ink** [comment] 2021-05-21 10:33
> Hey, Dude!
> Thanks for your issue. I''ll check your case into this week. is it big problem in your usage?
> Relax and don't flame

Big problem, hope fix quickly

**Comment by mrfoe7** [comment] 2021-05-21 12:53
same issue https://github.com/googollee/go-socket.io/issues/351

**Comment by googollee** [comment] 2021-05-21 19:51
It's caused by the code in https://github.com/googollee/go-socket.io/issues/399#issuecomment-830760492 which force the reader closing in 30 sec.

**Closed** 2021-05-21 21:39 UTC
Labels: bug, question, v2
