### ISSUE TITLE
Need specific tags for 0.9.x branch 

### ISSUE THREAD

**Issue by 0xCMP** [googollee/go-socket.io#142] opened 2016-08-21 07:49 UTC
Tag on 0.9.x branch prevent making easy pushes to 0.9.x branch because git can't tell if I'm trying to update/checkout/push the tag ref or the branch ref.

**Comment by erkie** [comment] 2019-02-08 10:26
Duplicate of https://github.com/googollee/go-socket.io/issues/142

**Comment by erkie** [comment] 2019-02-08 10:26
Oops meant https://github.com/googollee/go-socket.io/issues/133 hihi

**Closed by erkie** 2019-02-08 10:26 UTC
Labels: duplicate
